# Generated by Django 3.1.7 on 2021-03-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210307_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', height_field='400', null=True, upload_to='profile_images', width_field='400'),
        ),
    ]
