version: '3'

services:
  
  db:
    image: postgres:latest
    networks: ["web"]
    
    environment:
      - POSTGRES_USER=noobi
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog
  
  web:
    build: .
    networks: ["web"]
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

networks:
  web:
