#!/bin/sh

set -ex

project_name="blogPost"
project_dir=`pwd | grep -oE ".+${project_name}/"`
pip_bin_dir=`find ${project_dir} -type f -name "pip3" | grep -oE ".*/"`

if [[ $pip_bin_dir ]];then
    source $pip_bin_dir/activate
    pip install -r ${project_dir}/webapp/requirements.txt
    python3 ${project_dir}/webapp/manage.py collectstatic --noinput
    python3 ${project_dir}/webapp/manage.py makemigrations --noinput
    python3 ${project_dir}/webapp/manage.py migrate --noinput
else
    echo "virtual pip env not setup"
fi
