version: '3'

services:
  
  db:
    image: postgres:alpine
    networks: ["blogpost_web"]
    env_file:
      - ./.env.dev
  
  backend:
    build: .
    image: blogpost_backend
    environment:
      - STAGE=TESTING
      - RUN_PORT=8000
    networks: ["blogpost_web"]
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

networks:
  blogpost_web:
    external: true
